### ISSUE TITLE
Winium.StoreApps.Driver giving error on Windows10

### ISSUE THREAD

**Issue by Pranodayd** [2gis/Winium.StoreApps#151]
When I tried starting Winium.StoreApps.Driver.exe on Windows 10 machine I got the following error log:
```
14:13:16 [INFO] Winium.StoreApps.Driver, Version: 1.6.2.15006, Revision: efb0b81ea01243d898fcba88f99ca7513b7925ac
14:13:16 [FATAL] System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Xde.Common, Version=8.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Xde.Common, Version=8.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Winium.Mobile.Connectivity.Emulator.EmulatorFactory..ctor()
   at Winium.Mobile.Connectivity.Emulator.EmulatorFactory.<.cctor>b__0() in d:\Projects\windows-universal-app-driver\Winium\Winium.Mobile.Connectivity\Emulator\EmulatorFactory.cs:line 20
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Winium.StoreApps.Driver.Program.Main(String[] args) in d:\Projects\windows-universal-app-driver\Winium\Winium.StoreApps.Driver\Program.cs:line 63

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

Any Idea to resolve this issue?

Thanks and Regards,
Pranoday

**Comment by Pranodayd** [comment]
Could fix this problem.Installed required emulators and Microsoft SDKs.Please close this issue.
