### ISSUE TITLE
Could not clear data in Edit control

### ISSUE THREAD

**Issue by Pranodayd** [2gis/Winium.StoreApps#154]
Hi @NickAb .
I tried clearing data written in EditControl in Windows 10 application using WebElement.clear(); to which I got error:Not Implemented:clearElement.Also tried with WebElement.sendkeys(Keys.BACK_SPACE),it didnt succeed as well.

Can you please tell me any other way to achieve this using Winium.StoreApps.

Thanks and Regards,
Pranoday

**Comment by NickAb** [comment]
Just use `sendKeys` with empty string as parameter. Each `sendKeys` call 'resets' input and sets it to the new value.

The driver uses automation pattern to set text on element, so it is not actual text input key after key, this means that special keys, like <kbd>backspace</kbd> will not work. We do handle <kbd>enter</kbd>, <kbd>f1</kbd>, <kbd>f2</kbd> and <kbd>f3</kbd> as special cases, but they will always be inputed last, regardless of their position in text. You an find more details in [dirver implementation](https://github.com/2gis/Winium.StoreApps/blob/Winium/Winium.StoreApps.Driver/CommandExecutors/SendKeysToElementExecutor.cs) and in [inner server implementation](https://github.com/2gis/Winium.StoreApps/blob/Winium/Winium.StoreApps.InnerServer/Commands/ValueCommand.cs)

**Comment by Pranodayd** [comment]
Hi @NickAb 
SendKeys is not able to input values in numeric field(field after parking on which number pad of OS gets opened).How to handle this situation then?,because you said in your reply above that it does not simulate key press.In Android(using Appium) we handled this scenario using Keys and it is working fine there.
Please suggest.

**Comment by NickAb** [comment]
I will need to reproduce this issue, can you provide minimal XAML needed to create input similar to that with which you have a problem?

Meanwhile, one possible workaround is to use https://github.com/2gis/Winium.StoreApps/wiki/Command-Execute-Script#set-property-on-element to directly set property that holds the numeric value (but this is of course not a good solution).
If numpad is provided by OS, then its buttons will not be visible to driver, but still you can try calling `Page Source` when numpad is open and check for elements in xml that correspond to numpad keys. If by any chance they are available, then you will be able to click them using driver as a temporary workaround.

**Comment by Pranodayd** [comment]
@NickAb .I will try your workaround and will get back to you.

Thanks and Regards,
Pranoday

**Comment by Pranodayd** [comment]
Hi @NickAb 
I wanted to get numeric value typed in edit field hence used 
Driver.executeScript("attribute: set", ElementTobeClicked, "value", "10");

but this resulted in following stacktrace.

org.openqa.selenium.WebDriverException: {
  "error": "unknown error",
  "stacktrace": "   at Winium.StoreApps.InnerServer.Commands.CommandBase.InvokeSync(CoreDispatcher dispatcher, Action action)\r\n   at Winium.StoreApps.InnerServer.Commands.CommandBase.Do()",
  "message": "Could not access attribute value."
} (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 215 milliseconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'pranodaydwin81', ip: '10.9.6.94', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_92'
Driver info: org.openqa.selenium.winium.WiniumDriver
Capabilities [{app=D:\magic\UP2\RIAModules\Windows10Mobile\MagicDev\MagicApp_1.0.0.0_x86_Test\MagicApp_1.0.0.0_x86.appx, debugConnectToRunningApp=false, deviceName=Mobile Emulator 10.0.10586.0 720p 5 inch 1GB, launchTimeout=10000, commandSettings={elementAttributeSettings={accessModifier=ClrProperties, enumAsString=false}}, platform=ANY, dependencies=[], launchDelay=0, autoLaunch=true, noFallback=true, files={}, pingTimeout=2500, takesScreenshot=true, platformName=WindowsPhone}]
Session ID: 872e1e32-35ce-4200-86b1-6434cad367f6
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:577)
	at com.magicsoftware.TestAutomation.Utils.Utilities.EnterText_ByXpath_For_Winium(Utilities.java:5611)
	at com.magicsoftware.TestAutomation.WinMobileTest.EnterTextInTableControl(WinMobileTest.java:3260)
	at com.magicsoftware.TestAutomation.WinMobileTest.EnterTextInTableControlField(WinMobileTest.java:3218)
	at com.magicsoftware.TestAutomation.TestCases.Data_Controls.P50(Data_Controls.java:898)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
What could be the reason? May be I am setting wrong property value

Thanks and Regards,
Pranoday

**Comment by NickAb** [comment]
Could you please provide a bit of XAML to reproduce the numeric input?
I was able to successfully input number using `SendKeys` into numeric input created using following XAML
```xaml
<TextBox InputScope="Number" AutomationProperties.AutomationId="NumericInput"/>
```

**Comment by Pranodayd** [comment]
@NickAb .I need to ask my manager whether I can share it with you or not.I will ask and get back to you.

Thanks and Regards,
Pranoday

**Comment by NickAb** [comment]
Of course, it would be great if you could just create a minimal app with single input element that you have problem with, so that nothing else gets published.

**Comment by Pranodayd** [comment]
@NickAb Sure.Will get back to you on this

**Comment by NickAb** [comment]
@Pranodayd any updates on this one?
