### ISSUE TITLE
Cannot deploy WP10 appxbundle

### ISSUE THREAD

**Issue by maclogic** [2gis/Winium.StoreApps#182]
Hi Guys,

 I've been watching the videos, and scavenging over all the source code and I could not get my sample app test to run successfully. Its a simple Xamarin/UWP10 project. But it always fails on the constructor of the WpDriver  (code below). I'm using Winium.StoreApps.Driver v162.

 DesiredCapabilities cap = new DesiredCapabilities();
            cap.SetCapability("app", @"App001.UWP_1.0.1.0_x86_x64_arm_Debug.appxbundle");
            cap.SetCapability("deviceName", "Mobile Emulator 10.0.14393.0 WVGA 4 inch 512MB");            
            cap.SetCapability("debugConnectToRunningApp", true);

            oDriver = new WpDriver(new Uri("http://localhost:9999/"), cap);

The exception i get is the following:

"There is an error in XML document (30, 15). (33)"
trace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
   at UITest1.WpDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities) in C:\Users\Mac\Desktop\UITest1\WpDriver.cs:line 40
   at UITest1.WinniumTest.initialize() in C:\Users\Mac\Desktop\UITest1\WinniumTest.cs:line 43

Can you let me know what am I missing? (sample project attached).

[Sample.zip](https://github.com/2gis/Winium.Mobile/files/950058/Sample.zip)

**Comment by maclogic** [comment]
This seems to be the very same issue as described in https://github.com/2gis/Winium.Mobile/issues/116#issuecomment-162839134

I don't know if the only issue is the deployment, but if it is, I was able to deploy (to emulator) via command line:
"C:\Program Files (x86)\Windows Kits\10\bin\x86\WinAppDeployCmd.exe" install -file "App001.UWP_1.0.1.0_x86_x64_arm_Debug.appxbundle" -dependency "Dependencies\x86\\*.appx" -ip 172.16.80.2

Requisites for this command to work:
- Developer mode ON
- Device Discovery ON
- Device Portal ON (Auth OFF)
- Know the IP of the emulator device.

@NickAb, are there any plans on continuing developing this project?

**Comment by NickAb** [comment]
Hi, @maclogic.

Yes, I would like to add proper support for Windows 10 Mobile. I wanted to look at device portal #166 my self. Thanks for providing pre-requisites for it to work.

Do I understand correctly that device portal is only available on Windows 10 and is not available on Windows 8?

**Comment by maclogic** [comment]
@NickAb , I don't have a windows 8 phone to try on, I have a windows 10, but on the emulators i have for windows 8 I could not find the portal app, nor in any documentation that i've ever read for wp8 deployment, so i would risk to say yes.

I would happily provide screenshots for the device portal if it would help in anyway. Although i think the CMD line would be the way to go in this particular case :)

**Comment by NickAb** [comment]
@maclogic, thanks. Hopefully I will be able to look this issue this summer.
